version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-alphainsider-test
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/New_York
      - N8N_LOG_LEVEL=debug
      - N8N_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom
      - ./package.json:/home/node/.n8n/custom/package.json:ro

volumes:
  n8n_data: